### ISSUE TITLE
Exception: data did not match any variant of untagged enum ModelWrapper at line 1251019 column 3

### ISSUE THREAD

**Issue by sunnyyangyangyang** [camenduru/hunyuan-video-jupyter#3]
Traceback (most recent call last):
  File "/content/HunyuanVideo/sample_video.py", line 57, in <module>
    main()
  File "/content/HunyuanVideo/sample_video.py", line 25, in main
    hunyuan_video_sampler = HunyuanVideoSampler.from_pretrained(models_root_path, args=args)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/HunyuanVideo/hyvideo/inference.py", line 123, in from_pretrained
    text_encoder = TextEncoder(
                   ^^^^^^^^^^^^
  File "/content/HunyuanVideo/hyvideo/text_encoder/__init__.py", line 190, in __init__
    self.tokenizer, self.tokenizer_path = load_tokenizer(
                                          ^^^^^^^^^^^^^^^
  File "/content/HunyuanVideo/hyvideo/text_encoder/__init__.py", line 69, in load_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/models/auto/tokenization_auto.py", line 837, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/tokenization_utils_base.py", line 2086, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/tokenization_utils_base.py", line 2325, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/models/llama/tokenization_llama_fast.py", line 133, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/transformers/tokenization_utils_fast.py", line 111, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: data did not match any variant of untagged enum ModelWrapper at line 1251019 column 3

**Comment by camenduru** [comment]
please use this https://x.com/camenduru/status/1864602316373938350 (Runpod). It seems that Colab is not capable of running this project.
